site_name: Pawan Rajput | Jr. DevOps Engineer
site_description: Portfolio of Pawan Rajput, Jr. DevOps Engineer based in Gurugram.
site_author: Pawan Rajput
site_url: https://rajputpawan.github.io

nav:
  - Home: index.md
  - About: about.md
  - Skills: skills.md
  - Experience: experience.md
  - Projects: projects.md
  - Certifications: certifications.md
  - Contact: contact.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  font:
    text: Merriweather
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rajputpawan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajputpawan
    - icon: material/email
      link: mailto:rajput.pawan.personal@gmail.com

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

plugins:
  - search

extra_css:
  - assets/extra.css
